name: Deploy to Web

on:
  push:
    branches:
      - main
      - m3

jobs:
  web-deploy:
    name: Web Deploy
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - uses: subosito/flutter-action@v2
      - uses: sarbagyastha/flutter-gh-pages@main
        with:
          workingDir: example
          baseHref: /
          customArgs: --wasm